### ISSUE TITLE
Re-number "Introduction" section

### ISSUE THREAD

**Issue by anermina** [metanorma/ogc-citygml2#10]
Introduction section is numbered with 0 in original, while with X in generated document.

![image](https://user-images.githubusercontent.com/55683568/151430588-d78dadc5-fafe-4ca6-afba-92615e00adeb.png)

_From https://github.com/opengeospatial/ogc-metanorma-testing/issues/74#issuecomment-1022337828_

**Comment by opoudjis** [comment]
In OGC, the Introduction is part of the preface, and is numbered as part of the preface. Since this is the final section in the preface, it is given X. 

Numbering it as 0 instead is an ISO convention, and appears to inherit from ISO using 0 only when there are subsections to the introduction.

Metanorma shall not arbitrarily change numbering of sections from document to document. That is simply not a reasonable request, and it defeats the purpose of having a tool like Metanorma. 

If Introductions are (a) to be left without a Roman numeral, and (b) to have zero numbering if they have subclauses, and that is to be applied throughout OGC, I shall need explicit confirmation from this from OGC. Given that clauses can still appear after Introduction in a preface (such as executive summaries), and be numbered, that would be disastrous.

I am not going to work on this without more clarity from OGC.

**Comment by opoudjis** [comment]
@ghobona This is a legacy document, and custom formatting implementation is in our opinion a bad idea. It would be better to re-publish the CityGML 2 document with the updated format and then the Japanese translation.

**Comment by ghobona** [comment]
@opoudjis Ok, agreed. Comment withdrawn.
